<?php

namespace frontend\widgets\rating;

use yii\base\Widget;

class RatingWidget extends Widget
{
    public float $rating;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('stars', [
            'rating' => $this->rating
        ]);
    }


}