<?php

namespace frontend\widgets\status;

use yii\base\Widget;

class StatusWidget extends Widget
{
    public string $status;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('index', [
            'status' => $this->status
        ]);
    }

}